# Generated by normsexchange-dev/ai-agent-control; do not edit.
# Standard: 2026.08.30.1; source: bcb026242672a709d5c1397b8f6583d5bd845f34; configuration hash: 1212e8a26195230b1db6bfdb703860f1c4b42858f493a17d0c1cd30ccd00afdb
[CmdletBinding()]
param([string]$ControlRoot, [string]$NodePath, [string]$CapabilityProfile, [switch]$RefreshOps, [switch]$Offline)

$ErrorActionPreference = 'Stop'
$consumerRoot = Split-Path -Parent $PSScriptRoot
$manifestPath = Join-Path $PSScriptRoot 'manifest.json'

if (-not (Test-Path -LiteralPath $manifestPath)) {
    Write-Output 'SYSTEM EXCEPTION Agent configuration — NO-GO — installation manifest is missing.'
    exit 2
}

$manifest = Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json
$local = $null
$localPath = Join-Path $consumerRoot '.agent-control.local.json'
if (Test-Path -LiteralPath $localPath) {
    $local = Get-Content -Raw -LiteralPath $localPath | ConvertFrom-Json
}
if ([string]::IsNullOrWhiteSpace($ControlRoot)) {
    $ControlRoot = $env:AI_AGENT_CONTROL_ROOT
}
if ([string]::IsNullOrWhiteSpace($ControlRoot)) {
    if ($null -ne $local -and -not [string]::IsNullOrWhiteSpace($local.control_root)) {
        $ControlRoot = Join-Path $consumerRoot $local.control_root
    }
}

if ([string]::IsNullOrWhiteSpace($ControlRoot) -or -not (Test-Path -LiteralPath $ControlRoot)) {
    Write-Output ("Agent: {0}; installed standard: {1}" -f $(if ($null -eq $local) { 'unavailable' } else { $local.agent_id }), $manifest.installed_standard_version)
    Write-Output 'SYSTEM EXCEPTION Agent configuration — UNKNOWN — authoritative control repository is unavailable.'
    exit 3
}

$centralVerifier = Join-Path $ControlRoot 'scripts\verify-agent-config.ps1'
if (-not (Test-Path -LiteralPath $centralVerifier)) {
    Write-Output 'SYSTEM EXCEPTION Agent configuration — NO-GO — central verifier is missing.'
    exit 2
}

$parameters = @{ Target = $consumerRoot }
if ($null -ne $local -and -not [string]::IsNullOrWhiteSpace($local.agent_id)) { $parameters.AgentId = $local.agent_id }
if (-not [string]::IsNullOrWhiteSpace($manifest.project_id)) { $parameters.ProjectId = $manifest.project_id }
if (-not [string]::IsNullOrWhiteSpace($NodePath)) { $parameters.NodePath = $NodePath }
if (-not [string]::IsNullOrWhiteSpace($CapabilityProfile)) { $parameters.CapabilityProfile = $CapabilityProfile }
if ($RefreshOps) { $parameters.RefreshOps = $true }
if ($Offline) { $parameters.Offline = $true }
& $centralVerifier @parameters
exit $LASTEXITCODE
