# Generated by normsexchange-dev/ai-agent-control; do not edit.
# Standard: 2026.08.31.2; source: ef174a2eb1daa3441ad80b4d3985fd29a0c55664; configuration hash: f4500ab1621f73ec555822e7227fec73d89ecd8827744c831fc5480578f02814
[CmdletBinding()]
param(
    [string]$StateRoot = (Join-Path $env:LOCALAPPDATA 'NormsExchange\CodexUsageFinalizer_dev')
)

$ErrorActionPreference = 'Stop'

try {
    $inputText = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($inputText)) { throw 'Hook input is empty.' }
    $event = $inputText | ConvertFrom-Json -DateKind String
    if ([string]$event.hook_event_name -ne 'SessionEnd') { throw 'Unexpected hook event.' }
    $sessionId = [string]$event.session_id
    if ($sessionId -notmatch '^[A-Za-z0-9][A-Za-z0-9._-]{2,199}$') { throw 'Unsafe session ID.' }
    $rolloutPath = [string]$event.transcript_path
    if (-not $rolloutPath -or -not (Test-Path -LiteralPath $rolloutPath -PathType Leaf)) { throw 'Rollout file is unavailable.' }
    $eventRoot = Join-Path $StateRoot 'hook-events'
    New-Item -ItemType Directory -Path $eventRoot -Force | Out-Null
    $destination = Join-Path $eventRoot "session-$sessionId-end.json"
    $temporary = Join-Path $eventRoot (".session-$sessionId-$([Guid]::NewGuid().ToString('N')).tmp")
    $normalized = [ordered]@{
        schema_version = '1.0.0'
        hook_event_name = 'SessionEnd'
        session_id = $sessionId
        rollout_path = [IO.Path]::GetFullPath($rolloutPath)
        reason = if ($event.reason) { [string]$event.reason } else { 'other' }
        observed_at = [DateTimeOffset]::Now.ToString('o')
    }
    $normalized | ConvertTo-Json -Depth 3 | Set-Content -LiteralPath $temporary -Encoding utf8NoBOM
    Move-Item -LiteralPath $temporary -Destination $destination -Force
    Write-Output '{"continue":true}'
}
catch {
    Write-Error 'Codex usage lifecycle capture failed without exposing hook input.'
    exit 1
}
